fix(upgrade) : upgrade to hapi 17
vbudhram/hapi-hpkp pull request #2
Opened 2018-05-16 11:52 UTC by deeptibaghel

@vbudhram i am not able to upgrade this plugin to hapi 17, need your help please.

2018-05-16 11:54 UTC, deeptibaghel commented
Here is the error https://pastebin.com/UNVt6QxJ

2018-05-16 13:15 UTC, vladikoff commented
We figured out the `TypeError: server.inject is not a function` errors. 
@deeptibaghel let us know what others you are getting

(We should also add some CI to this repo later on)

2018-05-16 13:17 UTC, deeptibaghel commented
@vladikoff now it is :
1) HPKP Headers
       "before all" hook:
     Error: listen EADDRINUSE 0.0.0.0:3000
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at Server.setupListenHandle [as _listen2] (net.js:1367:14)
      at listenInCluster (net.js:1408:12)
      at doListen (net.js:1517:7)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) HPKP Headers
       "after all" hook:
     TypeError: Cannot read property 'stop' of undefined
      at Context.<anonymous> (tests/index.js:92:21)

2018-05-16 14:32 UTC, vladikoff commented
@deeptibaghel quick tip, for future work make sure to create feature branches for your changes:

![image](https://user-images.githubusercontent.com/128755/40123456-4c23cd18-58f4-11e8-9411-f6bf1f62d65b.png)

so instead of `master`, it can be something like `hapi17-update`. This is useful to keep organized

2018-05-16 14:34 UTC, deeptibaghel commented
@vladikoff yeah i will take care, i do generally for other repos , will do for all now.

2018-05-16 15:06 UTC, vbudhram commented
@deeptibaghel Looks like there are a few things that need to be updated to get this plugin hapi 17 compatible.

From https://tech.xogrp.com/migrating-to-hapi-v17-plugin-structure-and-glue-manifests-a7b3c3d551f2, plugins are registered differently so we will need to update this to new format.

We will also have to update the test server as well.

2018-05-16 15:12 UTC, vladikoff commented
some updates listed here: https://github.com/vbudhram/hapi-hpkp/pull/3/files

2018-05-16 15:28 UTC, vladikoff commented on tests/index.js
> +      return createServer(3000, testCase.options).then((s) => {
@deeptibaghel before merging this let's clean this up to maybe use `before/after` again. More importantly let's see if this plugin works in the fxa-auth-server before merging :)

2018-05-18 14:02 UTC, vbudhram commented
@deeptibaghel I updated some of the tests that were causing port conflicts, rebase when you get a chance and see if they are still failing for you.

2018-06-19 14:39 UTC, vladikoff requested changes
Need some changes and a rebase

2018-06-19 14:39 UTC, vladikoff commented on package.json
> +    "hapi": "17.4.0",
let's update to latest hapi version here

2018-06-19 14:39 UTC, vladikoff commented on tests/index.js
> +  }catch(err){
spacse between `} catch(err) {`

2018-06-19 14:39 UTC, vladikoff commented on tests/index.js
>      handler: function (request, reply) {
should the wait be before `server.route` or before the function here in the handler? `handler: await function`

2018-06-19 14:39 UTC, vladikoff commented on tests/index.js
> +  await server.start()
👍

2018-06-19 14:39 UTC, vladikoff commented on tests/index.js
> +      return createServer(3000, testCase.options).then((s) => {
Still applies, let's clean this up

2018-06-21 13:30 UTC, closed without merging