Upgrade to hapi 17
vbudhram/hapi-hpkp pull request #5
Opened 2018-06-21 13:26 UTC by deeptibaghel

2018-06-21 16:12 UTC, vladikoff commented
@vbudhram r? so we can use it with hapi 17 in auth and oauth

2018-06-21 20:04 UTC, vbudhram requested changes
@deeptibaghel Looks good! Could you update the README example, something along these lines

```javascript
  try{
   await server.register({
      plugin: require('../index.js'),
      options: hpkpOptions
    })
  } catch(err) {
    console.error('Failed to load plugin:', err)
}
```

2018-06-21 20:04 UTC, vbudhram commented on tests/index.js
> +
Could remove extra line break.

2018-06-25 15:05 UTC, vbudhram commented on README.md
> +          plugin: require('../index.js'),
For this example, I think this should be `plugin: hpkp`.

2018-06-25 15:06 UTC, vbudhram reviewed
@deeptibaghel Just the one thing and this should be good. Once merged, I can tag a new release.

2018-06-26 17:49 UTC, merged

2018-06-26 17:50 UTC, vbudhram commented
@deeptibaghel Nice work!